server:
  port: 8989

spring:
  application:
    name: travel
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travels?characterEncoding=utf-8
    username: root
    password: 200088lx
  resources:
    static-locations: file:${upload.dir}


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: world.lixiang.travels.entity


upload:
  dir: D:/image